#!/bin/sh
#PBS -N CLC_Q_fs_SF_72
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=1:mem=1gb
#PBS -J 0-999
cp $PBS_O_WORKDIR/closed_loop_deg_single_SF.ce $TMPDIR
./closed_loop_deg_single_SF.ce 888376 72 1000 $PBS_ARRAY_INDEX 0.3 1000 0.0 33.12 0.00378514285714 808.0 1.24165230759e-05 0.023 1.0 1.00003162278
cp output_72_$PBS_ARRAY_INDEX.txt $PBS_O_WORKDIR/p072
sleep 10
rm $PBS_O_WORKDIR/CLC_Q_fs_SF_*
