#!/bin/sh
#PBS -N CLC_Q_fs_SD_22
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=1:mem=1gb
#PBS -J 0-999
cp $PBS_O_WORKDIR/closed_loop_deg_single_SD.ce $TMPDIR
./closed_loop_deg_single_SD.ce 66020 22 1000 $PBS_ARRAY_INDEX 0.3 1000 0.0 33.12 0.000599904714678 965.0 1.24165230759e-05 0.023 1.0 1.0316227766
cp output_22_$PBS_ARRAY_INDEX.txt $PBS_O_WORKDIR/p022
sleep 10
rm $PBS_O_WORKDIR/CLC_Q_fs_SD_*
