#!/bin/sh
#PBS -N CLC_Q_fs_SD_60
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=1:mem=1gb
#PBS -J 0-999
cp $PBS_O_WORKDIR/closed_loop_deg_single_SD.ce $TMPDIR
./closed_loop_deg_single_SD.ce 66020 60 1000 $PBS_ARRAY_INDEX 0.3 1000 0.0 33.12 0.00238826368562 873.0 1.24165230759e-05 0.023 1.0 1.00031622777
cp output_60_$PBS_ARRAY_INDEX.txt $PBS_O_WORKDIR/p060
sleep 10
rm $PBS_O_WORKDIR/CLC_Q_fs_SD_*
